# fly.toml app configuration file generated for section-hub-app
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'section-hub-app'
primary_region = 'fra'

[build]
  depot = false

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

  [http_service.response.headers]
    "Content-Security-Policy" = "frame-ancestors https://*.myshopify.com https://admin.shopify.com https://section-hub-app.fly.dev;"

[[http_service.checks]]
  protocol = 'http'
  method = 'GET'
  path = '/'
  interval = '10s'
  timeout = '5s'
  grace_period = '30s'

[[mounts]]
  source = "sqlite_data"
  destination = "/data"

[[statics]]
  guest_path = "/app/public/previews"
  url_prefix = "/previews"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
