// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/subscriptions_update": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/billing/subscription-complete": {
    params: {};
  };
  "/app/api/cancel-subscription": {
    params: {};
  };
  "/app/api/cleanup-previews": {
    params: {};
  };
  "/app/api/purchase-section": {
    params: {};
  };
  "/app/api/blocks-settings": {
    params: {};
  };
  "/app/api/install-section": {
    params: {};
  };
  "/app/api/purchase-bundle": {
    params: {};
  };
  "/app/api/install-block": {
    params: {};
  };
  "/app/billing/complete": {
    params: {};
  };
  "/app/api/try-section": {
    params: {};
  };
  "/app/image-optimizer": {
    params: {};
  };
  "/app/api/subscribe": {
    params: {};
  };
  "/app/api/contact": {
    params: {};
  };
  "/app/my-sections": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/section-ai": {
    params: {};
  };
  "/app/analyzer": {
    params: {};
  };
  "/app/bundles": {
    params: {};
  };
  "/app/explore": {
    params: {};
  };
  "/app/premium": {
    params: {};
  };
  "/app/section": {
    params: {};
  };
  "/app/suggest": {
    params: {};
  };
  "/app/updates": {
    params: {};
  };
  "/app/blocks": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/subscriptions_update" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/auth/login" | "/privacy" | "/auth/*" | "/app" | "/app/billing/subscription-complete" | "/app/api/cancel-subscription" | "/app/api/cleanup-previews" | "/app/api/purchase-section" | "/app/api/blocks-settings" | "/app/api/install-section" | "/app/api/purchase-bundle" | "/app/api/install-block" | "/app/billing/complete" | "/app/api/try-section" | "/app/image-optimizer" | "/app/api/subscribe" | "/app/api/contact" | "/app/my-sections" | "/app/additional" | "/app/section-ai" | "/app/analyzer" | "/app/bundles" | "/app/explore" | "/app/premium" | "/app/section" | "/app/suggest" | "/app/updates" | "/app/blocks" | "/app/help";
  };
  "routes/webhooks.app.subscriptions_update.tsx": {
    id: "routes/webhooks.app.subscriptions_update";
    page: "/webhooks/app/subscriptions_update";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/billing/subscription-complete" | "/app/api/cancel-subscription" | "/app/api/cleanup-previews" | "/app/api/purchase-section" | "/app/api/blocks-settings" | "/app/api/install-section" | "/app/api/purchase-bundle" | "/app/api/install-block" | "/app/billing/complete" | "/app/api/try-section" | "/app/image-optimizer" | "/app/api/subscribe" | "/app/api/contact" | "/app/my-sections" | "/app/additional" | "/app/section-ai" | "/app/analyzer" | "/app/bundles" | "/app/explore" | "/app/premium" | "/app/section" | "/app/suggest" | "/app/updates" | "/app/blocks" | "/app/help";
  };
  "routes/app.billing.subscription-complete.tsx": {
    id: "routes/app.billing.subscription-complete";
    page: "/app/billing/subscription-complete";
  };
  "routes/app.api.cancel-subscription.tsx": {
    id: "routes/app.api.cancel-subscription";
    page: "/app/api/cancel-subscription";
  };
  "routes/app.api.cleanup-previews.tsx": {
    id: "routes/app.api.cleanup-previews";
    page: "/app/api/cleanup-previews";
  };
  "routes/app.api.purchase-section.tsx": {
    id: "routes/app.api.purchase-section";
    page: "/app/api/purchase-section";
  };
  "routes/app.api.blocks-settings.tsx": {
    id: "routes/app.api.blocks-settings";
    page: "/app/api/blocks-settings";
  };
  "routes/app.api.install-section.tsx": {
    id: "routes/app.api.install-section";
    page: "/app/api/install-section";
  };
  "routes/app.api.purchase-bundle.tsx": {
    id: "routes/app.api.purchase-bundle";
    page: "/app/api/purchase-bundle";
  };
  "routes/app.api.install-block.tsx": {
    id: "routes/app.api.install-block";
    page: "/app/api/install-block";
  };
  "routes/app.billing.complete.tsx": {
    id: "routes/app.billing.complete";
    page: "/app/billing/complete";
  };
  "routes/app.api.try-section.tsx": {
    id: "routes/app.api.try-section";
    page: "/app/api/try-section";
  };
  "routes/app.image-optimizer.tsx": {
    id: "routes/app.image-optimizer";
    page: "/app/image-optimizer";
  };
  "routes/app.api.subscribe.tsx": {
    id: "routes/app.api.subscribe";
    page: "/app/api/subscribe";
  };
  "routes/app.api.contact.tsx": {
    id: "routes/app.api.contact";
    page: "/app/api/contact";
  };
  "routes/app.my-sections.tsx": {
    id: "routes/app.my-sections";
    page: "/app/my-sections";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.section-ai.tsx": {
    id: "routes/app.section-ai";
    page: "/app/section-ai";
  };
  "routes/app.analyzer.tsx": {
    id: "routes/app.analyzer";
    page: "/app/analyzer";
  };
  "routes/app.bundles.tsx": {
    id: "routes/app.bundles";
    page: "/app/bundles";
  };
  "routes/app.explore.tsx": {
    id: "routes/app.explore";
    page: "/app/explore";
  };
  "routes/app.premium.tsx": {
    id: "routes/app.premium";
    page: "/app/premium";
  };
  "routes/app.section.tsx": {
    id: "routes/app.section";
    page: "/app/section";
  };
  "routes/app.suggest.tsx": {
    id: "routes/app.suggest";
    page: "/app/suggest";
  };
  "routes/app.updates.tsx": {
    id: "routes/app.updates";
    page: "/app/updates";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.blocks.tsx": {
    id: "routes/app.blocks";
    page: "/app/blocks";
  };
  "routes/app.help.tsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.subscriptions_update": typeof import("./app/routes/webhooks.app.subscriptions_update.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.billing.subscription-complete": typeof import("./app/routes/app.billing.subscription-complete.tsx");
  "routes/app.api.cancel-subscription": typeof import("./app/routes/app.api.cancel-subscription.tsx");
  "routes/app.api.cleanup-previews": typeof import("./app/routes/app.api.cleanup-previews.tsx");
  "routes/app.api.purchase-section": typeof import("./app/routes/app.api.purchase-section.tsx");
  "routes/app.api.blocks-settings": typeof import("./app/routes/app.api.blocks-settings.tsx");
  "routes/app.api.install-section": typeof import("./app/routes/app.api.install-section.tsx");
  "routes/app.api.purchase-bundle": typeof import("./app/routes/app.api.purchase-bundle.tsx");
  "routes/app.api.install-block": typeof import("./app/routes/app.api.install-block.tsx");
  "routes/app.billing.complete": typeof import("./app/routes/app.billing.complete.tsx");
  "routes/app.api.try-section": typeof import("./app/routes/app.api.try-section.tsx");
  "routes/app.image-optimizer": typeof import("./app/routes/app.image-optimizer.tsx");
  "routes/app.api.subscribe": typeof import("./app/routes/app.api.subscribe.tsx");
  "routes/app.api.contact": typeof import("./app/routes/app.api.contact.tsx");
  "routes/app.my-sections": typeof import("./app/routes/app.my-sections.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.section-ai": typeof import("./app/routes/app.section-ai.tsx");
  "routes/app.analyzer": typeof import("./app/routes/app.analyzer.tsx");
  "routes/app.bundles": typeof import("./app/routes/app.bundles.tsx");
  "routes/app.explore": typeof import("./app/routes/app.explore.tsx");
  "routes/app.premium": typeof import("./app/routes/app.premium.tsx");
  "routes/app.section": typeof import("./app/routes/app.section.tsx");
  "routes/app.suggest": typeof import("./app/routes/app.suggest.tsx");
  "routes/app.updates": typeof import("./app/routes/app.updates.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.blocks": typeof import("./app/routes/app.blocks.tsx");
  "routes/app.help": typeof import("./app/routes/app.help.tsx");
};